### ISSUE TITLE
Al acceder al estudio de colores no aparecen los audios

### ISSUE THREAD

**Issue by carloscmor** [Dani-gr/MIAU#36]
Sólo pasa al entrar la primera vez en la página, ya que si se pulsa el botón de "Más colores" aparecen los audios en la otra paleta, y si se vuelve a pulsar vuelve a aparecer en la primera de ellas. Estoy revisando el .js correspondiente porque creo que tiene que ver con button.onClick.

**Comment by Dani-gr** [comment]
Joé, a mí sí me iban, pero ahora no...

**Comment by carloscmor** [comment]
Cierro la Issue porque lo acabo de solucionar. Resulta que el miércoles pasado se retiraron los audios del html para que no se reprodujeran todos libremente al inicio del estudio; por lo que al cargar la página por primera vez no hay audios, ya que el método inicializador de js no los carga, y sólo eran cargados cuando se pulsaba el botón de cambiar a la otra paleta. ¿Cúal es la solución? pues insertar la carga de audios también en el método inicial (el que se invoca tras pulsar el botón de inicio de estudio), por lo que ahora todo vuelve a funcionar perfectamente !!
