### ISSUE TITLE
Practice mode instead of Adventure Mode

### ISSUE THREAD

**Issue by carloscmor** [Dani-gr/MIAU#5]
Creo que la pantalla que se llama "Practice Mode" (estudiar) debería llamarse "Adventure Mode" (jugar) para seguir el [https://www.figma.com/file/VNjJ1V5UKYCjmITg2FJw74/Untitled?node-id=0-1&t=RWt6x8Z5Hszxc3PD-0](prototipo de MIAU)

**Comment by Nu36** [comment]
Pero me parece recordar que dijimos que lo del prototipo estaba mal, que iban a ser estudiar (la parte de estudio) y practica (lo del mapa)

**Comment by carloscmor** [comment]
Cierto todo.
